name: package

on:
  push:
    branches:
      - package
    paths:
      - .github/workflows/package.yaml
  workflow_dispatch:

concurrency:
  group: package
  cancel-in-progress: false

jobs:
  package:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        version:
          - "0.3.21"
    steps:
      - name: Checkout version
        uses: actions/checkout@v3
        with:
          ref: v${{ matrix.version }}

      - name: Install fpm
        run: |
          echo "::group::Install fpm"
          sudo gem install fpm
          echo "::endgroup::"

          echo "::group::Show fpm version"
          fpm --version
          echo "::endgroup::"

      - name: Build goss
        run: |
          echo "::group::Build goss release"
          make release/goss-linux-amd64
          echo "::endgroup::"

          echo "::group::Verify goss checksum"
          pushd release
          sha256sum --check goss-linux-amd64.sha256
          echo "::endgroup::"

      - name: Package goss
        run: |
          echo "::group::Package goss deb"
          fpm \
            --input-type dir \
            --output-type deb \
            --name goss \
            --architecture amd64 \
            --version ${{ matrix.version }} \
            release/goss-linux-amd64=/usr/local/bin/goss
          echo "::endgroup::"

          echo "::group::Show goss deb"
          dpkg --contents goss_${{ matrix.version }}_amd64.deb
          echo "::endgroup::"

          echo "::group::Install goss"
          dpkg --install goss_${{ matrix.version }}_amd64.deb
          echo "::endgroup::"

          echo "::group::Run goss"
          /usr/local/bin/goss --help
          /usr/local/bin/goss --version
          echo "::endgroup::"
