name: package

on:
  push:
    branches:
      - package
    paths:
      - .github/workflows/package.yaml
  workflow_dispatch:

concurrency:
  group: package
  cancel-in-progress: false

jobs:
  package:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        version:
          - "0.3.21"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v${{ matrix.version }}

      - name: Install fpm
        run: |
          sudo gem install fpm
          fpm --version

      - name: Build goss
        run: |
          make release/goss-linux-amd64
          pushd release
          sha256sum --check goss-linux-amd64.sha256

      - name: Package goss
        run: |
          fpm \
            --input-type dir \
            --output-type deb \
            --name goss \
            --architecture amd64 \
            --version ${{ matrix.version }} \
            release/goss-linux-amd64=/usr/local/bin/goss
          dpkg --contents gossl_${{ matrix.version }}_amd64.deb
