name: package

on:
  push:
    branches:
      - package
    paths:
      - .github/workflows/package.yaml
  workflow_dispatch:

concurrency:
  group: package
  cancel-in-progress: false

jobs:
  package:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install fpm
        run: |
          sudo gem install fpm
          fpm --version

      - name: Build goss
        run: |
          make release/goss-linux-amd64
          sha256sum --check release/goss-linux-amd64.sha256
